landing                 : false
title                   : Site title
author                  : Your Name
url                     : "https://www.yoursiteurl.com"
author_url              : "https://www.yoururl.com"
baseurl                 : "/" 
timezone                : "Europe/Madrid"
description             : Short description of your site.
full_description        : >
 A long description of your site.
gh_repository           : https://github.com/yourusername/yourrepo/
encoding                : "utf-8"
locale                  : "en-US"
lang                    : "en"
formemail               : "form@email.com"
email                   : "you@email.com"
permalink               : pretty

# Manifest
name                    : "Site name"
short_name              : "NAME"
language                : "en"
lang_direction          : "ltr"
color                   : "#FFFFFF"

# Add your Social Profiles
twitter_username        :
github_username         : 
linkedin_username       : 
kofi                    : 

# Add your google-analytics ID here to activate google analytics
google_site_verification: 
google_analytics        : 
google_adsense_account  : 
google_tag_id           : 

# Disqus Comments. Leave shortname blank to disable comments site-wide.
# Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
disqus_shortname        : 


# Theme Notice (please don't remove it ;))
theme_version           : v2.0.0
theme_name              : NOCC Bootstrap Jekyll Theme
theme_repo              : https://github.com/carlesloriente/jekyll-theme-nocc/
theme_url               : https://bootstrap-theme.notesoncloudcomputing.com/
theme_author            : Carles Loriente
theme_author_url        : https://www.notesoncloudcomputing.com/about/
theme_download          : https://github.com/carlesloriente/jekyll-theme-nocc/archive/refs/heads/main.zip
theme_package           : https://rubygems.org/gems/jekyll-theme-nocc
theme_logo              : "/assets/vendor/nocc-bootstrap-theme/images/nocc/nocc_logo.webp"

# Site settings
includes_dir            : _includes
layouts_dir             : _layouts
plugins_dir             : _plugins
tags_dir                : tags

collections:
  posts:
    permalink           : /posts/:name/
    output              : true
  tags:
    permalink           : /tags/:name/
    output              : true

defaults:
  - scope:
      path              : "posts"
      type              : posts
    values:
      layout            : post
  - scope:
      path              : 'assets/**'
    values:
      sitemap           : false

# Markdown Processors
kramdown:
  auto_ids              : true
  entity_output         : as_char
  toc_levels            : [1, 2, 3, 4, 5, 6]
  smart_quotes          : lsquo,rsquo,ldquo,rdquo
  input                 : GFM
  hard_wrap             : false
  footnote_nr           : 1
  show_warnings         : false

# Build settings
paginate                : 20
paginate_path           : "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

sass:
  load_paths:
    - ./_sass
  style                 : compressed

exclude: ["AUTHORS.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "CODEOWNERS", "LICENSE", "README.md", "SECURITY.md", "WORKFLOW.md", "Gemfile", "Gemfile.lock", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]