name: Publish Gem

on:
  push:
    branches:
      - "!*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          RUBYGEMS_API_KEY: ${{ secrets.RG_GHACTION_API_KEY }}
          RELEASE_COMMAND: rake release
