name: Build and Publish Gem

on:
  push:
    branches:
      - "!*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v1
      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          RUBYGEMS_API_KEY: ${{ secrets.RG_GHACTION_API_KEY }}
          RELEASE_COMMAND: rake release
      - name: Configure git user
        run: |
          git config --global user.email "7197733+carlesloriente@users.noreply.github.com"
          git config --global user.name "Carles Loriente"
