name: Publish Gem

on:
  push:
    branches:
      - "!*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v1
      - name: Release Gem
        if: contains(github.ref, 'refs/tags/v')
        uses: cadwallion/publish-rubygems-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          RUBYGEMS_API_KEY: ${{ secrets.RG_GHACTION_API_KEY }}
          RELEASE_COMMAND: rake release
          OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
          OWNER_NAME: ${{ secrets.OWNER_NAME }}
          run: |
            git config --global user.email "$OWNER_EMAIL"
            git config --global user.name "$OWNER_NAME"
