name: Build and Publish Gem

on:
  push:
    branches:
      - "!*"
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      id-token: write

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - uses: rubygems/release-gem@v1